/**
 * generated by Xtext 2.13.0
 */
package org.example.entities.validation;

import java.util.HashSet;
import org.eclipse.xtext.validation.Check;
import org.eclipse.xtext.xbase.lib.CollectionLiterals;
import org.example.entities.entities.Attribute;
import org.example.entities.entities.EntitiesPackage;
import org.example.entities.entities.Entity;
import org.example.entities.validation.AbstractEntitiesValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class EntitiesValidator extends AbstractEntitiesValidator {
  protected final static String ISSUE_CODE_PREFIX = "org.example.entities.";
  
  public final static String HIERARCHY_CYCLE = (EntitiesValidator.ISSUE_CODE_PREFIX + "HierarchyCycle");
  
  public final static String INVALID_ENTITY_NAME = (EntitiesValidator.ISSUE_CODE_PREFIX + "InvalidEntityName");
  
  public final static String INVALID_ATTRIBUTE_NAME = (EntitiesValidator.ISSUE_CODE_PREFIX + "InvalidAttributeName");
  
  @Check
  public void checkNoCycleInEntityHierarchy(final Entity entity) {
    Entity _superType = entity.getSuperType();
    boolean _tripleEquals = (_superType == null);
    if (_tripleEquals) {
      return;
    }
    final HashSet<Entity> visitedEntities = CollectionLiterals.<Entity>newHashSet(entity);
    Entity current = entity.getSuperType();
    while ((current != null)) {
      {
        boolean _contains = visitedEntities.contains(current);
        if (_contains) {
          String _name = current.getName();
          String _plus = ("cycle in hierarchy of entity \'" + _name);
          String _plus_1 = (_plus + "\'");
          this.error(_plus_1, EntitiesPackage.eINSTANCE.getEntity_SuperType(), 
            EntitiesValidator.HIERARCHY_CYCLE, current.getSuperType().getName());
          return;
        }
        visitedEntities.add(current);
        current = current.getSuperType();
      }
    }
  }
  
  @Check
  public void checkEntityNameStartsWithCapital(final Entity entity) {
    boolean _isLowerCase = Character.isLowerCase(entity.getName().charAt(0));
    if (_isLowerCase) {
      char _upperCase = Character.toUpperCase(entity.getName().charAt(0));
      String _plus = ("Entity name should start with a capital \'" + Character.valueOf(_upperCase));
      String _plus_1 = (_plus + "\'");
      this.warning(_plus_1, 
        EntitiesPackage.eINSTANCE.getEntity_Name(), EntitiesValidator.INVALID_ENTITY_NAME, entity.getName());
    }
  }
  
  @Check
  public void checkAttributeNameStartsWithLowercase(final Attribute attr) {
    boolean _isUpperCase = Character.isUpperCase(attr.getName().charAt(0));
    if (_isUpperCase) {
      char _upperCase = Character.toUpperCase(attr.getName().charAt(0));
      String _plus = ("Attribute name should start with a lowercase\'" + Character.valueOf(_upperCase));
      String _plus_1 = (_plus + "\'");
      this.warning(_plus_1, 
        EntitiesPackage.eINSTANCE.getAttribute_Name(), EntitiesValidator.INVALID_ATTRIBUTE_NAME, attr.getName());
    }
  }
}
